export interface DiseaseInfo {
  id: string
  name: string
  description: string
  symptoms: string[]
  causes: string[]
  treatments: string[]
  prevention: string[]
  whenToSeeDoctor: string[]
  severity: "common" | "moderate" | "serious"
  image: string
}

export const diseases: DiseaseInfo[] = [
  {
    id: "acne",
    name: "Acne",
    description:
      "A skin condition that occurs when hair follicles become plugged with oil and dead skin cells. It causes whiteheads, blackheads, or pimples.",
    symptoms: [
      "Whiteheads (closed plugged pores)",
      "Blackheads (open plugged pores)",
      "Small red, tender bumps (papules)",
      "Pimples (pustules) with pus at tips",
      "Large, solid, painful lumps under skin (nodules)",
      "Painful, pus-filled lumps under skin (cystic lesions)",
    ],
    causes: [
      "Excess oil (sebum) production",
      "Hair follicles clogged by oil and dead skin cells",
      "Bacteria",
      "Hormonal changes",
      "Certain medications",
      "Diet high in refined sugars or carbohydrates",
    ],
    treatments: [
      "Over-the-counter topical treatments (benzoyl peroxide, salicylic acid)",
      "Prescription topical medications (retinoids, antibiotics)",
      "Oral medications (antibiotics, birth control pills, isotretinoin)",
      "Light therapy",
      "Chemical peels",
      "Steroid injections for severe acne",
    ],
    prevention: [
      "Wash your face twice daily with mild cleanser",
      "Use oil-free, water-based skin care products",
      "Remove makeup before sleeping",
      "Avoid touching your face frequently",
      "Shower after strenuous activities",
      "Maintain a healthy diet",
    ],
    whenToSeeDoctor: [
      "Over-the-counter treatments dont work after several weeks",
      "Acne is severe (deep, painful cysts)",
      "Acne is leaving scars",
      "Acne appeared suddenly in adulthood",
    ],
    severity: "common",
    image: "/acne-skin-condition.jpg",
  },
  {
    id: "eczema",
    name: "Eczema (Atopic Dermatitis)",
    description:
      "A condition that makes skin red, inflamed, and itchy. It is common in children but can occur at any age. Eczema is chronic and tends to flare periodically.",
    symptoms: [
      "Dry, cracked, scaly skin",
      "Itching, which may be severe",
      "Red to brownish-gray patches",
      "Small, raised bumps that may leak fluid",
      "Thickened, cracked skin",
      "Raw, sensitive, swollen skin from scratching",
    ],
    causes: [
      "Genetic factors",
      "Immune system dysfunction",
      "Environmental triggers",
      "Dry skin",
      "Bacterial infections",
      "Stress and hormones",
    ],
    treatments: [
      "Moisturizing regularly",
      "Topical corticosteroid creams",
      "Calcineurin inhibitors",
      "Systemic medications for severe cases",
      "Light therapy (phototherapy)",
      "Wet wrap therapy",
    ],
    prevention: [
      "Moisturize skin at least twice daily",
      "Identify and avoid triggers",
      "Take shorter baths or showers",
      "Use gentle soaps without dyes or perfumes",
      "Dry yourself carefully after bathing",
      "Wear soft, breathable clothing",
    ],
    whenToSeeDoctor: [
      "Symptoms are so uncomfortable they affect sleep",
      "Skin appears infected (red streaks, pus, yellow scabs)",
      "Home remedies havent helped",
      "Eczema affects daily activities",
    ],
    severity: "moderate",
    image: "/eczema-atopic-dermatitis-skin.jpg",
  },
  {
    id: "psoriasis",
    name: "Psoriasis",
    description:
      "A skin disease that causes red, itchy scaly patches, most commonly on the knees, elbows, trunk, and scalp. It speeds up the life cycle of skin cells.",
    symptoms: [
      "Red patches of skin covered with thick, silvery scales",
      "Small scaling spots",
      "Dry, cracked skin that may bleed",
      "Itching, burning, or soreness",
      "Thickened or ridged nails",
      "Swollen and stiff joints",
    ],
    causes: [
      "Immune system dysfunction (T cells attack healthy skin)",
      "Genetics",
      "Environmental triggers",
      "Stress",
      "Skin injuries",
      "Certain medications",
    ],
    treatments: [
      "Topical corticosteroids",
      "Vitamin D analogues",
      "Retinoids",
      "Light therapy",
      "Oral or injected medications",
      "Biologics",
    ],
    prevention: [
      "Moisturize daily",
      "Avoid triggers (stress, smoking, heavy alcohol)",
      "Get moderate sun exposure",
      "Maintain a healthy weight",
      "Avoid skin injuries",
      "Manage stress levels",
    ],
    whenToSeeDoctor: [
      "Condition becomes severe or widespread",
      "Causes significant discomfort",
      "Joint problems develop",
      "Current treatment stops working",
    ],
    severity: "moderate",
    image: "/psoriasis-skin-patches.jpg",
  },
  {
    id: "ringworm",
    name: "Ringworm (Tinea)",
    description:
      "A contagious fungal infection of the skin characterized by ring-shaped, red, scaly patches. Despite its name, it is not caused by a worm.",
    symptoms: [
      "Ring-shaped, flat patch of itchy skin",
      "Clear or scaly area inside the ring",
      "Expanding rings",
      "Round, flat patch of itchy skin",
      "Overlapping rings",
      "Raised, blistering patches",
    ],
    causes: [
      "Fungal infection (dermatophytes)",
      "Person-to-person contact",
      "Animal-to-person contact",
      "Object-to-person contact",
      "Soil-to-person contact",
      "Warm, moist environments",
    ],
    treatments: [
      "Antifungal creams, lotions, or powders",
      "Prescription topical medications",
      "Oral antifungal medications",
      "Keep affected area clean and dry",
      "Apply treatment for 2-4 weeks",
      "Continue treatment 1-2 weeks after symptoms clear",
    ],
    prevention: [
      "Keep skin clean and dry",
      "Dont share towels, clothing, or sports gear",
      "Wear flip-flops in public showers",
      "Change socks and underwear daily",
      "Avoid touching pets with bald spots",
      "Wash hands after touching animals",
    ],
    whenToSeeDoctor: [
      "Infection doesnt improve within 2 weeks of treatment",
      "Infection spreads to other areas",
      "Signs of bacterial infection appear",
      "You have diabetes or weakened immune system",
    ],
    severity: "common",
    image: "/ringworm-fungal-infection-skin.jpg",
  },
  {
    id: "rosacea",
    name: "Rosacea",
    description:
      "A common skin condition causing redness and visible blood vessels in the face. It may also produce small, red, pus-filled bumps.",
    symptoms: [
      "Facial redness (flushing)",
      "Visible blood vessels",
      "Swollen bumps resembling acne",
      "Eye problems (dryness, irritation)",
      "Enlarged nose (rhinophyma)",
      "Burning or stinging sensation",
    ],
    causes: [
      "Genetics",
      "Blood vessel abnormalities",
      "Microscopic mites (Demodex)",
      "H. pylori bacteria",
      "Environmental factors",
      "Immune system reactions",
    ],
    treatments: [
      "Topical medications (brimonidine, azelaic acid)",
      "Oral antibiotics",
      "Isotretinoin",
      "Laser therapy",
      "IPL (Intense Pulsed Light)",
      "Electrosurgery",
    ],
    prevention: [
      "Identify and avoid personal triggers",
      "Protect face from sun",
      "Use gentle skin care products",
      "Avoid alcohol and spicy foods",
      "Manage stress",
      "Use green-tinted makeup to conceal redness",
    ],
    whenToSeeDoctor: [
      "Persistent facial redness",
      "Bumps or pimples on face",
      "Eye irritation or vision problems",
      "Thickening skin on nose",
    ],
    severity: "moderate",
    image: "/rosacea-facial-redness.jpg",
  },
  {
    id: "melanoma",
    name: "Melanoma",
    description:
      "The most serious type of skin cancer, developing in cells that give skin its color. It can also form in the eyes and rarely in internal organs.",
    symptoms: [
      "Change in existing mole",
      "Development of new pigmented growth",
      "Asymmetrical mole shape",
      "Irregular, ragged borders",
      "Color variation within mole",
      "Diameter larger than 6mm",
    ],
    causes: [
      "UV light exposure (sun, tanning beds)",
      "Fair skin with less melanin",
      "History of sunburns",
      "Many moles or unusual moles",
      "Family history of melanoma",
      "Weakened immune system",
    ],
    treatments: [
      "Surgical removal",
      "Immunotherapy",
      "Targeted therapy",
      "Radiation therapy",
      "Chemotherapy",
      "Clinical trials",
    ],
    prevention: [
      "Avoid sun during peak hours",
      "Wear sunscreen year-round",
      "Wear protective clothing",
      "Avoid tanning beds",
      "Check skin regularly for changes",
      "Know your risk factors",
    ],
    whenToSeeDoctor: [
      "New skin growth appears",
      "Existing mole changes in size, shape, or color",
      "Mole becomes itchy or bleeds",
      "Spot that looks different from others",
      "Any suspicious skin changes",
    ],
    severity: "serious",
    image: "/melanoma-skin-cancer-mole.jpg",
  },
  {
    id: "hives",
    name: "Hives (Urticaria)",
    description:
      "A skin reaction causing itchy welts ranging from small spots to large blotches. Hives can be triggered by many situations and substances.",
    symptoms: [
      "Raised, itchy bumps (wheals)",
      "Red or skin-colored welts",
      "Welts that vary in size and shape",
      "Welts that appear and fade repeatedly",
      "Swelling (angioedema)",
      "Painful swelling of lips, eyelids, throat",
    ],
    causes: [
      "Allergic reactions (food, medications)",
      "Infections",
      "Insect stings or bites",
      "Physical triggers (pressure, cold, heat)",
      "Stress",
      "Unknown causes (chronic idiopathic urticaria)",
    ],
    treatments: [
      "Antihistamines",
      "Anti-itch medications",
      "Corticosteroids",
      "Epinephrine for severe reactions",
      "Omalizumab (Xolair) for chronic hives",
      "Avoidance of triggers",
    ],
    prevention: [
      "Identify and avoid known triggers",
      "Keep a diary of outbreaks",
      "Wear loose, lightweight clothing",
      "Apply cool compresses",
      "Avoid hot baths or showers",
      "Manage stress",
    ],
    whenToSeeDoctor: [
      "Hives last more than a few days",
      "Hives keep recurring",
      "Difficulty breathing or swallowing",
      "Dizziness or lightheadedness",
      "Hives dont respond to treatment",
    ],
    severity: "common",
    image: "/hives-urticaria-skin-welts.jpg",
  },
  {
    id: "vitiligo",
    name: "Vitiligo",
    description:
      "A condition causing loss of skin color in patches. It occurs when melanocytes (cells that produce melanin) die or stop functioning.",
    symptoms: [
      "Patchy loss of skin color",
      "Premature whitening of hair",
      "Loss of color in mouth and nose tissues",
      "Change in eye color",
      "Patches typically start on sun-exposed areas",
      "Progressive spreading of patches",
    ],
    causes: [
      "Autoimmune disorder",
      "Genetic factors",
      "Trigger events (stress, sunburn)",
      "Exposure to chemicals",
      "Neural factors",
      "Oxidative stress",
    ],
    treatments: [
      "Topical corticosteroids",
      "Calcineurin inhibitors",
      "Light therapy (PUVA, UVB)",
      "Depigmentation therapy",
      "Skin grafting",
      "Tattooing (micropigmentation)",
    ],
    prevention: [
      "Protect skin from sun",
      "Avoid artificial tanning",
      "Use sunscreen regularly",
      "Dont get tattoos (may trigger new patches)",
      "Manage stress",
      "No known way to prevent initial occurrence",
    ],
    whenToSeeDoctor: [
      "Notice areas of skin, hair, or eyes losing color",
      "Patches are spreading",
      "Want to discuss treatment options",
      "Emotional distress about appearance",
    ],
    severity: "moderate",
    image: "/vitiligo-skin-patches.jpg",
  },
  {
    id: "chicken-skin",
    name: "Chicken Skin (Keratosis Pilaris)",
    description:
      "A common, harmless skin condition that causes dry, rough patches and tiny bumps, often on the upper arms, thighs, cheeks, or buttocks. The bumps usually don't hurt or itch and resemble goosebumps or the skin of a plucked chicken.",
    symptoms: [
      "Small, painless bumps on skin",
      "Dry, rough patches",
      "Bumps that feel like sandpaper",
      "Skin-colored, white, red, or brown bumps",
      "Worsening in winter or dry conditions",
      "Slight pinkness or redness around bumps",
    ],
    causes: [
      "Buildup of keratin (a protein that protects skin)",
      "Genetic predisposition",
      "Associated with dry skin",
      "Often occurs with eczema or allergies",
      "Hormonal changes",
      "Vitamin A deficiency",
    ],
    treatments: [
      "Moisturizing creams with urea or lactic acid",
      "Exfoliating with alpha hydroxy acids (AHAs)",
      "Topical retinoids to promote cell turnover",
      "Gentle exfoliation with a loofah or pumice stone",
      "Laser therapy for severe redness",
      "Microdermabrasion",
    ],
    prevention: [
      "Keep skin well moisturized",
      "Use a humidifier in dry environments",
      "Take lukewarm showers instead of hot",
      "Use gentle, fragrance-free cleansers",
      "Exfoliate regularly but gently",
      "Avoid tight clothing that causes friction",
    ],
    whenToSeeDoctor: [
      "Bumps become infected or inflamed",
      "Condition affects self-esteem significantly",
      "Over-the-counter treatments dont help",
      "Bumps spread to new areas rapidly",
    ],
    severity: "common",
    image: "/chicken-skin-keratosis-pilaris.jpg",
  },
  {
    id: "wart",
    name: "Wart",
    description:
      "A small, grainy skin growth caused by the human papillomavirus (HPV). Warts are benign and can appear anywhere on the body but are most common on hands and feet. They are contagious and can spread through direct contact.",
    symptoms: [
      "Small, fleshy, grainy bumps",
      "Flesh-colored, white, pink, or tan growths",
      "Rough to the touch",
      "Black pinpoints (clotted blood vessels)",
      "Single or clustered growths",
      "May cause discomfort when on feet (plantar warts)",
    ],
    causes: [
      "Human papillomavirus (HPV) infection",
      "Direct contact with warts",
      "Touching contaminated surfaces",
      "Breaks in the skin allow virus entry",
      "Weakened immune system",
      "Nail biting or picking at hangnails",
    ],
    treatments: [
      "Over-the-counter salicylic acid treatments",
      "Cryotherapy (freezing with liquid nitrogen)",
      "Cantharidin application by doctor",
      "Electrosurgery and curettage",
      "Laser treatment",
      "Immunotherapy for stubborn warts",
    ],
    prevention: [
      "Avoid touching warts (yours or others)",
      "Keep hands and feet dry",
      "Wear flip-flops in public showers and pools",
      "Dont share towels or personal items",
      "Avoid biting nails or picking at cuticles",
      "Keep skin healthy and moisturized",
    ],
    whenToSeeDoctor: [
      "Wart is painful or changes appearance",
      "Warts spread or recur despite treatment",
      "Warts interfere with daily activities",
      "You have diabetes or weakened immune system",
      "Unsure if growth is actually a wart",
      "Warts appear on face or genitals",
    ],
    severity: "common",
    image: "/wart-skin-growth.jpg",
  },
]

export const getSuggestions = (disease: string, severity: "mild" | "moderate" | "severe"): string[] => {
  const diseaseData = diseases.find((d) => d.name.toLowerCase().includes(disease.toLowerCase()))

  // Extended recommendations database for various skin conditions
  const extendedRecommendations: Record<string, { mild: string[]; moderate: string[]; severe: string[] }> = {
    acne: {
      mild: [
        "Wash your face twice daily with a gentle, non-comedogenic cleanser",
        "Apply over-the-counter benzoyl peroxide (2.5-5%) to affected areas",
        "Use oil-free moisturizers and sunscreen",
        "Avoid touching your face throughout the day",
        "Change pillowcases frequently to reduce bacteria buildup",
        "Stay hydrated and maintain a balanced diet low in processed foods",
      ],
      moderate: [
        "Consider using salicylic acid or adapalene (Differin) gel",
        "Schedule a consultation with a dermatologist for prescription options",
        "Use non-comedogenic makeup and remove it before bed",
        "Apply spot treatments containing sulfur or tea tree oil",
        "Consider dietary changes - reduce dairy and high-glycemic foods",
        "Be patient - most treatments take 6-8 weeks to show results",
      ],
      severe: [
        "URGENT: See a dermatologist for prescription-strength treatment",
        "Avoid picking or squeezing lesions to prevent scarring",
        "Ask about oral antibiotics or isotretinoin (Accutane)",
        "Consider hormonal therapy if applicable",
        "Professional extraction or cortisone injections may help",
        "Document your skin condition for medical appointments",
      ],
    },
    eczema: {
      mild: [
        "Apply fragrance-free moisturizer immediately after bathing",
        "Use lukewarm water instead of hot water for bathing",
        "Choose soft, breathable fabrics like cotton",
        "Use a humidifier to add moisture to dry indoor air",
        "Apply 1% hydrocortisone cream for itchy patches",
        "Identify and avoid personal triggers (detergents, stress, allergens)",
      ],
      moderate: [
        "Consult a dermatologist for prescription topical steroids",
        "Consider wet wrap therapy for stubborn patches",
        "Ask about calcineurin inhibitors (Protopic, Elidel)",
        "Take antihistamines to help with nighttime itching",
        "Keep nails short to minimize damage from scratching",
        "Consider patch testing to identify contact allergens",
      ],
      severe: [
        "URGENT: Seek dermatologist care - may need systemic treatment",
        "Watch for signs of infection (oozing, increased redness, fever)",
        "Ask about dupilumab (Dupixent) or other biologics",
        "Phototherapy may be recommended for widespread eczema",
        "Consider allergy testing for comprehensive management",
        "Join a support group - chronic eczema can affect mental health",
      ],
    },
    psoriasis: {
      mild: [
        "Apply thick moisturizers or petroleum jelly to plaques",
        "Use medicated shampoos with coal tar or salicylic acid for scalp",
        "Get moderate sun exposure (10-15 minutes daily)",
        "Take daily baths with colloidal oatmeal or Epsom salts",
        "Apply over-the-counter hydrocortisone for inflammation",
        "Avoid skin injuries - they can trigger new plaques (Koebner phenomenon)",
      ],
      moderate: [
        "See a dermatologist for prescription topical treatments",
        "Ask about vitamin D analogues (calcipotriene)",
        "Consider phototherapy (UVB light treatment)",
        "Manage stress through meditation or exercise",
        "Limit alcohol consumption which can worsen flares",
        "Track triggers in a journal to identify patterns",
      ],
      severe: [
        "URGENT: Consult a dermatologist for systemic treatment options",
        "Biologics (Humira, Cosentyx, Taltz) may be recommended",
        "Watch for joint pain - could indicate psoriatic arthritis",
        "Regular monitoring of liver function if on certain medications",
        "Consider joining clinical trials for new treatments",
        "Screen for comorbidities (heart disease, diabetes, depression)",
      ],
    },
    ringworm: {
      mild: [
        "Apply over-the-counter antifungal cream (clotrimazole, miconazole)",
        "Keep the affected area clean and dry",
        "Wash hands thoroughly after touching the infection",
        "Avoid sharing towels, clothing, or personal items",
        "Continue treatment for 1-2 weeks after symptoms clear",
        "Wash bedding and clothes in hot water to kill fungal spores",
      ],
      moderate: [
        "Use prescription-strength antifungal cream if OTC fails",
        "Apply antifungal powder to prevent moisture buildup",
        "See a doctor if infection covers a large area",
        "Consider oral antifungals for scalp or nail involvement",
        "Disinfect combs, brushes, and hair accessories",
        "Check household members and pets for infection",
      ],
      severe: [
        "URGENT: See a doctor for oral antifungal medication",
        "Scalp ringworm requires oral treatment - topicals won't penetrate",
        "Complete the full course of medication even if symptoms improve",
        "Watch for signs of bacterial superinfection",
        "May need 4-8 weeks of treatment for complete resolution",
        "Follow up to ensure the infection is fully cleared",
      ],
    },
    rosacea: {
      mild: [
        "Use gentle, fragrance-free cleansers and moisturizers",
        "Apply SPF 30+ sunscreen daily - sun is a major trigger",
        "Identify and avoid personal triggers (spicy food, alcohol, heat)",
        "Use green-tinted primer to neutralize redness",
        "Avoid extreme temperatures and hot beverages",
        "Choose mineral-based makeup over chemical formulations",
      ],
      moderate: [
        "Consult a dermatologist for prescription topical treatments",
        "Ask about brimonidine gel or oxymetazoline for redness",
        "Azelaic acid can help with bumps and redness",
        "Consider low-dose oral antibiotics for anti-inflammatory effect",
        "Avoid alcohol-based skincare products",
        "LED light therapy may help reduce inflammation",
      ],
      severe: [
        "URGENT: See a dermatologist - aggressive treatment needed",
        "IPL (Intense Pulsed Light) or laser therapy for blood vessels",
        "Oral isotretinoin for severe papulopustular rosacea",
        "Surgical options available for rhinophyma (nose thickening)",
        "Monitor for ocular rosacea - can affect vision",
        "Long-term maintenance therapy usually required",
      ],
    },
    melanoma: {
      mild: [
        "Schedule a dermatologist appointment for professional evaluation",
        "Take clear photos of the suspicious spot for monitoring",
        "Follow the ABCDE rule: Asymmetry, Border, Color, Diameter, Evolution",
        "Don't delay - early detection dramatically improves outcomes",
        "Protect the area from sun exposure",
        "Inform family members - melanoma can run in families",
      ],
      moderate: [
        "URGENT: Schedule immediate dermatology appointment",
        "A biopsy is needed to confirm or rule out melanoma",
        "Avoid any trauma to the suspicious lesion",
        "Document the spot's changes with dated photographs",
        "Prepare questions for your dermatology visit",
        "Consider getting a second opinion if diagnosis is uncertain",
      ],
      severe: [
        "EMERGENCY: Seek immediate specialist care",
        "Melanoma is highly treatable when caught early",
        "Surgical excision is usually the first treatment step",
        "Sentinel lymph node biopsy may be needed",
        "Ask about immunotherapy and targeted therapy options",
        "Build a support network - oncology social workers can help",
      ],
    },
    hives: {
      mild: [
        "Take over-the-counter antihistamines (cetirizine, loratadine)",
        "Apply cool compresses to soothe itching",
        "Wear loose, comfortable clothing",
        "Avoid known triggers and keep a symptom diary",
        "Take lukewarm showers - hot water can worsen hives",
        "Try to identify if a recent food, medication, or stress caused them",
      ],
      moderate: [
        "See a doctor if hives last more than 6 weeks",
        "Consider adding an H2 blocker (famotidine) to H1 antihistamine",
        "Ask about prescription-strength antihistamines",
        "Allergy testing may help identify triggers",
        "Avoid NSAIDs which can worsen hives in some people",
        "Consider stress management techniques",
      ],
      severe: [
        "EMERGENCY: Call 911 if experiencing difficulty breathing or swallowing",
        "Carry an epinephrine auto-injector if prescribed",
        "Corticosteroids may be needed for severe episodes",
        "Ask about omalizumab (Xolair) for chronic hives",
        "See an allergist/immunologist for comprehensive evaluation",
        "Develop an action plan for future episodes",
      ],
    },
    vitiligo: {
      mild: [
        "Apply SPF 30+ sunscreen to protect depigmented skin from burns",
        "Use cosmetic camouflage makeup for even skin tone if desired",
        "Consult a dermatologist to discuss treatment options",
        "Some cases may repigment naturally, especially in younger patients",
        "Avoid tattoos which can trigger new patches (Koebner phenomenon)",
        "Join support communities - vitiligo is not contagious or harmful",
      ],
      moderate: [
        "Ask about topical corticosteroids or calcineurin inhibitors",
        "Narrowband UVB phototherapy can stimulate repigmentation",
        "Consider combination therapies for better results",
        "Treatment works best on face and trunk, less on hands/feet",
        "Be patient - repigmentation takes several months",
        "Protect treated areas from sun to prevent contrast",
      ],
      severe: [
        "Consult a specialist for comprehensive treatment planning",
        "Excimer laser therapy for localized areas",
        "Consider surgical options: skin grafting or melanocyte transplants",
        "Depigmentation therapy may be an option for extensive vitiligo",
        "Seek psychological support if appearance changes affect well-being",
        "New JAK inhibitors showing promising results in clinical trials",
      ],
    },
    // Additional skin conditions commonly detected by models
    "athlete's foot": {
      mild: [
        "Apply over-the-counter antifungal cream, spray, or powder",
        "Keep feet clean and thoroughly dry, especially between toes",
        "Wear breathable shoes and moisture-wicking socks",
        "Change socks daily, more often if feet sweat heavily",
        "Use antifungal powder in shoes to prevent reinfection",
        "Wear flip-flops in public showers and pool areas",
      ],
      moderate: [
        "See a doctor if infection persists after 2 weeks of OTC treatment",
        "Prescription-strength topical antifungals may be needed",
        "Soak feet in diluted white vinegar or tea tree oil solution",
        "Rotate shoes to allow them to dry completely between wears",
        "Treat shoes with antifungal spray or UV shoe sanitizer",
        "Check for and treat toenail fungus simultaneously",
      ],
      severe: [
        "URGENT: See a doctor - may need oral antifungal medication",
        "Watch for signs of bacterial infection (increased pain, swelling, pus)",
        "Complete full course of prescribed medication",
        "Severe cases may indicate underlying health issues",
        "Diabetics should seek prompt medical care for any foot infection",
        "Consider podiatrist referral for chronic cases",
      ],
    },
    cellulitis: {
      mild: [
        "See a doctor promptly - antibiotics are typically required",
        "Elevate the affected limb to reduce swelling",
        "Apply cool, damp cloths for comfort",
        "Mark the edges of redness to monitor spreading",
        "Take all prescribed antibiotics as directed",
        "Rest and stay hydrated",
      ],
      moderate: [
        "URGENT: Seek medical care today - cellulitis can spread quickly",
        "May require stronger or IV antibiotics",
        "Watch for signs of worsening (fever, spreading redness, increased pain)",
        "Keep the affected area clean and covered",
        "Address any underlying skin conditions that may cause breaks in skin",
        "Follow up with your doctor within 48-72 hours",
      ],
      severe: [
        "EMERGENCY: Seek immediate medical attention",
        "Hospitalization may be needed for IV antibiotics",
        "Watch for signs of sepsis (high fever, confusion, rapid heart rate)",
        "Surgical drainage may be required for abscesses",
        "Imaging may be needed to rule out deeper infection",
        "Do not delay treatment - severe cellulitis can be life-threatening",
      ],
    },
    impetigo: {
      mild: [
        "See a doctor - antibiotic treatment speeds healing and reduces spread",
        "Gently wash sores with soap and water, then cover loosely",
        "Wash hands frequently to prevent spreading",
        "Don't share towels, bedding, or personal items",
        "Keep children home from school/daycare until treated for 24 hours",
        "Apply prescribed antibiotic ointment as directed",
      ],
      moderate: [
        "Oral antibiotics may be needed for more extensive infection",
        "Keep affected areas covered with gauze and medical tape",
        "Trim fingernails short to reduce scratching damage",
        "Watch for signs of spread or worsening",
        "Clean toys and surfaces that may be contaminated",
        "Complete the full antibiotic course even if sores heal",
      ],
      severe: [
        "URGENT: See a doctor - ecthyma (deeper form) may be developing",
        "IV antibiotics may be needed in rare cases",
        "Watch for signs of post-strep complications",
        "Scarring may occur with deeper infections",
        "Follow up to ensure complete resolution",
        "Address any underlying skin conditions that increase risk",
      ],
    },
    herpes: {
      mild: [
        "See a doctor for antiviral medication (valacyclovir, acyclovir)",
        "Keep the affected area clean and dry",
        "Avoid touching sores, wash hands if you do",
        "Apply over-the-counter topical treatments for symptom relief",
        "Avoid intimate contact during active outbreaks",
        "Cold compresses can help with discomfort",
      ],
      moderate: [
        "Start antiviral medication at first sign of outbreak",
        "Suppressive therapy may be recommended for frequent outbreaks",
        "Stay hydrated and get adequate rest",
        "Manage stress which can trigger outbreaks",
        "Talk to your doctor about preventive medication",
        "Inform partners about your status for their health",
      ],
      severe: [
        "URGENT: See a doctor immediately for severe or widespread infection",
        "IV antivirals may be needed for disseminated herpes",
        "Watch for signs of herpes keratitis (eye involvement)",
        "Immunocompromised patients need prompt aggressive treatment",
        "Severe outbreaks may require pain management",
        "Consider suppressive therapy to reduce future outbreaks",
      ],
    },
    scabies: {
      mild: [
        "See a doctor for prescription scabicide (permethrin cream)",
        "Apply treatment to entire body from neck down, not just itchy areas",
        "Leave medication on for 8-14 hours, usually overnight",
        "Wash all bedding, clothing, and towels in hot water",
        "Vacuum furniture and carpets, discard vacuum bag",
        "Itching may continue for weeks after successful treatment",
      ],
      moderate: [
        "All household members and close contacts should be treated",
        "Repeat treatment as directed, usually after 1 week",
        "Items that can't be washed should be sealed in plastic bags for 7 days",
        "Antihistamines can help with persistent itching",
        "Ask about oral ivermectin for difficult cases",
        "Avoid skin-to-skin contact until treatment is complete",
      ],
      severe: [
        "URGENT: Crusted (Norwegian) scabies requires aggressive treatment",
        "Multiple treatments with permethrin and oral ivermectin needed",
        "This form is highly contagious - strict isolation may be needed",
        "Hospital admission may be required in severe cases",
        "Often associated with immunocompromised conditions",
        "Environmental decontamination is crucial",
      ],
    },
    warts: {
      mild: [
        "Many warts resolve on their own within 1-2 years",
        "Over-the-counter salicylic acid treatments can be effective",
        "Cover warts to prevent spread to other areas",
        "Don't pick at warts - this can spread the virus",
        "Keep the area clean and dry",
        "Duct tape occlusion therapy may help (cover wart for 6 days)",
      ],
      moderate: [
        "See a doctor if OTC treatments fail after 3 months",
        "Cryotherapy (freezing) is a common in-office treatment",
        "Multiple treatments are usually needed",
        "Cantharidin (blister beetle extract) causes wart to blister off",
        "Consider treatment for cosmetically bothersome or spreading warts",
        "Genital warts require medical evaluation and specific treatments",
      ],
      severe: [
        "Consult a dermatologist for resistant or widespread warts",
        "Laser therapy or electrosurgery for stubborn warts",
        "Immunotherapy (injecting antigens into warts) can help",
        "Investigate possible immune deficiency with many warts",
        "Surgical excision for unresponsive warts",
        "Some warts, especially genital, require cancer screening",
      ],
    },
    folliculitis: {
      mild: [
        "Apply warm compresses to affected areas for 15-20 minutes, 3-4 times daily",
        "Use antibacterial soap or benzoyl peroxide wash",
        "Avoid shaving irritated areas until healed",
        "Wear loose, breathable clothing",
        "Change out of sweaty clothes promptly after exercise",
        "Apply over-the-counter antibiotic ointment if needed",
      ],
      moderate: [
        "See a doctor if infection doesn't improve within a week",
        "Prescription topical or oral antibiotics may be needed",
        "For fungal folliculitis, antifungal treatments are required",
        "Use a new razor blade each time you shave",
        "Consider laser hair removal for recurrent cases",
        "Tea tree oil or white vinegar soaks may help mild cases",
      ],
      severe: [
        "URGENT: Deep folliculitis (boils, carbuncles) needs medical care",
        "Incision and drainage may be necessary",
        "Culture may be needed to identify resistant bacteria (MRSA)",
        "Longer course of antibiotics typically required",
        "Watch for signs of spreading infection",
        "Recurrent infections may need investigation for underlying causes",
      ],
    },
    dermatitis: {
      mild: [
        "Identify and avoid the irritant or allergen causing the reaction",
        "Apply fragrance-free moisturizer multiple times daily",
        "Use over-the-counter hydrocortisone cream for inflammation",
        "Take cool baths with colloidal oatmeal for relief",
        "Wear protective gloves when handling irritants",
        "Switch to hypoallergenic soaps and detergents",
      ],
      moderate: [
        "See a dermatologist for prescription-strength treatments",
        "Patch testing can help identify contact allergens",
        "Prescription topical steroids may be needed for flares",
        "Wet wrap therapy for stubborn patches",
        "Antihistamines can help with itching",
        "Consider occupational factors that may be contributing",
      ],
      severe: [
        "URGENT: Severe contact dermatitis may need oral steroids",
        "Watch for signs of secondary infection",
        "Hospitalization rarely needed but possible for widespread cases",
        "Phototherapy for chronic dermatitis",
        "Immunosuppressants for severe refractory cases",
        "Comprehensive allergen avoidance plan needed",
      ],
    },
    shingles: {
      mild: [
        "See a doctor within 72 hours - antivirals are most effective early",
        "Apply cool, wet compresses to blisters for relief",
        "Take over-the-counter pain relievers as directed",
        "Keep the rash clean and covered with loose bandages",
        "Avoid contact with unvaccinated individuals, especially pregnant women",
        "Wear loose, natural-fiber clothing",
      ],
      moderate: [
        "Antiviral medication (valacyclovir, acyclovir) reduces severity",
        "Ask about prescription pain relief for nerve pain",
        "Calamine lotion can soothe itching",
        "Capsaicin cream may help with post-herpetic neuralgia",
        "Rest is important for recovery",
        "Get the shingles vaccine after recovery to prevent recurrence",
      ],
      severe: [
        "URGENT: Shingles near the eye needs immediate evaluation",
        "IV antivirals may be needed for disseminated shingles",
        "Nerve blocks or strong pain medication for severe pain",
        "Watch for bacterial superinfection of blisters",
        "Post-herpetic neuralgia may require long-term pain management",
        "Immunocompromised patients need aggressive treatment",
      ],
    },
    carbuncle: {
      mild: [
        "Apply warm compresses for 20 minutes several times daily",
        "Never squeeze or attempt to drain a carbuncle yourself",
        "Keep the area clean with antibacterial soap",
        "Cover with a clean, dry bandage",
        "Take over-the-counter pain relievers as needed",
        "See a doctor - carbuncles often need medical treatment",
      ],
      moderate: [
        "Medical drainage is usually required",
        "Oral antibiotics are typically prescribed",
        "Continue warm compresses after drainage",
        "Change bandages as directed to keep wound clean",
        "Watch for signs of spreading infection",
        "Complete full antibiotic course",
      ],
      severe: [
        "URGENT: Large or worsening carbuncles need immediate care",
        "Surgical drainage under local anesthesia",
        "Culture to identify bacteria (often Staphylococcus)",
        "IV antibiotics for extensive infection",
        "Screen for diabetes which increases risk",
        "Recurrent carbuncles may indicate carrier status or immune issues",
      ],
    },
    seborrheic_dermatitis: {
      mild: [
        "Use over-the-counter dandruff shampoo with zinc pyrithione or selenium sulfide",
        "Shampoo daily and leave on scalp for 5 minutes before rinsing",
        "For face/body, use antifungal cream (ketoconazole)",
        "Moisturize flaky areas with gentle, fragrance-free lotion",
        "Avoid harsh soaps and skincare products",
        "Manage stress which can trigger flares",
      ],
      moderate: [
        "See a dermatologist if OTC treatments aren't helping",
        "Prescription antifungal shampoos or creams may be needed",
        "Low-potency topical steroids for inflammation",
        "Rotate different medicated shampoos to prevent resistance",
        "Consider phototherapy for stubborn cases",
        "Address any underlying conditions (Parkinson's, HIV) that worsen it",
      ],
      severe: [
        "Consult a dermatologist for comprehensive treatment",
        "Stronger prescription medications may be required",
        "Combination therapy with antifungals and anti-inflammatories",
        "Watch for secondary bacterial infection",
        "Scalp lesions may need overnight treatments",
        "Systemic antifungals rarely needed for resistant cases",
      ],
    },
    lupus: {
      mild: [
        "Protect skin from sun - UV light triggers flares",
        "Use SPF 50+ sunscreen and protective clothing",
        "See a rheumatologist for proper diagnosis and monitoring",
        "Anti-inflammatory medications may help skin symptoms",
        "Get adequate rest and manage stress",
        "Document symptoms and triggers for your doctor",
      ],
      moderate: [
        "Topical corticosteroids or calcineurin inhibitors for skin lesions",
        "Antimalarials (hydroxychloroquine) often used for skin lupus",
        "Regular blood tests to monitor disease activity",
        "Avoid smoking which worsens lupus",
        "Consider vitamin D supplementation",
        "Work with healthcare team to manage all aspects of lupus",
      ],
      severe: [
        "URGENT: Severe lupus rash may indicate systemic flare",
        "Systemic immunosuppressants may be needed",
        "Biologics (belimumab) available for lupus",
        "Monitor for kidney and other organ involvement",
        "Multidisciplinary care often needed",
        "Join lupus support groups for coping strategies",
      ],
    },
    keratosis_pilaris: {
      mild: [
        "This is a harmless condition and often improves with age",
        "Use gentle, fragrance-free moisturizers daily",
        "Apply moisturizer while skin is still damp from bathing",
        "Use lukewarm water - hot water dries skin",
        "Exfoliate gently with a soft washcloth",
        "Don't pick or scratch the bumps",
      ],
      moderate: [
        "Use lotions containing urea, lactic acid, or salicylic acid",
        "Alpha hydroxy acid (AHA) products help remove dead skin",
        "Apply moisturizer with retinol to promote cell turnover",
        "Use a humidifier in dry environments",
        "Avoid tight clothing that causes friction",
        "See a dermatologist for prescription retinoids if needed",
      ],
      severe: [
        "Consult a dermatologist for prescription treatments",
        "Laser therapy can reduce redness and improve texture",
        "Microdermabrasion or chemical peels may help",
        "Prescription retinoids for stubborn cases",
        "Usually doesn't require treatment unless cosmetically bothersome",
        "Patience is key - improvement takes time",
      ],
    },
    boil: {
      mild: [
        "Apply warm, moist compresses for 10-15 minutes, 3-4 times daily",
        "Never squeeze or lance a boil yourself",
        "Keep the area clean with antibacterial soap",
        "Cover with a sterile bandage",
        "Wash hands before and after touching the boil",
        "Most small boils heal on their own within 2 weeks",
      ],
      moderate: [
        "See a doctor if the boil is larger than a golf ball",
        "Medical drainage may be needed for larger boils",
        "Antibiotics may be prescribed if infection is spreading",
        "Apply antibiotic ointment after drainage",
        "Change bandages frequently",
        "Watch for fever or worsening symptoms",
      ],
      severe: [
        "URGENT: Large boils or boils on face need prompt medical care",
        "Facial boils can spread to the brain - take seriously",
        "Surgical drainage under local anesthesia",
        "Culture to check for MRSA (resistant staph)",
        "Longer antibiotic course for deep infections",
        "Recurrent boils need investigation for underlying causes",
      ],
    },
    sunburn: {
      mild: [
        "Get out of the sun immediately to prevent further damage",
        "Apply cool compresses or take cool baths",
        "Use aloe vera gel or moisturizing lotion liberally",
        "Stay hydrated by drinking plenty of water",
        "Take ibuprofen for pain and inflammation",
        "Wear loose, soft clothing over sunburned areas",
      ],
      moderate: [
        "Don't pop blisters - they protect healing skin",
        "Apply antibiotic ointment to broken blisters",
        "Continue moisturizing frequently as skin heals",
        "Avoid further sun exposure until completely healed",
        "Take cool baths with colloidal oatmeal for relief",
        "See a doctor if blisters cover a large area",
      ],
      severe: [
        "URGENT: Seek medical care for severe sunburn with fever or chills",
        "Watch for signs of sun poisoning (nausea, confusion, fainting)",
        "May need prescription pain relief or steroids",
        "IV fluids may be needed for severe dehydration",
        "This level of burn significantly increases skin cancer risk",
        "After healing, commit to rigorous sun protection",
      ],
    },
  }

  // Try to find matching extended recommendations
  const normalizedDisease = disease.toLowerCase().replace(/[_-]/g, " ").trim()
  
  // Find matching key in extended recommendations
  let matchedKey: string | null = null
  for (const key of Object.keys(extendedRecommendations)) {
    const normalizedKey = key.toLowerCase().replace(/[_-]/g, " ")
    if (normalizedDisease.includes(normalizedKey) || normalizedKey.includes(normalizedDisease)) {
      matchedKey = key
      break
    }
  }

  if (matchedKey) {
    return extendedRecommendations[matchedKey][severity]
  }

  // Fall back to disease data if available
  if (diseaseData) {
    const relevantTreatments = diseaseData.treatments.slice(0, 3)
    const relevantPrevention = diseaseData.prevention.slice(0, 2)

    if (severity === "severe") {
      return [
        "URGENT: Schedule an appointment with a dermatologist immediately",
        "Do not self-medicate without professional guidance",
        ...relevantTreatments,
        "Consider taking time off work/school if condition is affecting daily life",
        "Document symptoms and progression for your doctor",
      ]
    } else if (severity === "moderate") {
      return [
        "Schedule an appointment with a dermatologist within the next week",
        ...relevantTreatments,
        ...relevantPrevention,
        "Monitor the condition and note any changes",
      ]
    } else {
      return [
        "Consult with a dermatologist for proper diagnosis",
        "Keep the affected area clean and dry",
        ...relevantPrevention,
        "Avoid scratching or irritating the affected area",
        "Take photos to track progression over time",
      ]
    }
  }

  // Default recommendations if no specific data found
  const baseSuggestions: Record<"mild" | "moderate" | "severe", string[]> = {
    mild: [
      "Consult with a dermatologist for proper diagnosis and treatment plan",
      "Keep the affected area clean and gently moisturized",
      "Avoid scratching or irritating the affected area",
      "Take photos to track progression over time",
      "Use gentle, fragrance-free skincare products",
      "Monitor for any changes or worsening of symptoms",
    ],
    moderate: [
      "Schedule an appointment with a dermatologist within the next week",
      "Keep the affected area clean and protected",
      "Avoid self-treating without professional guidance",
      "Document the condition's progression for your appointment",
      "Identify and avoid potential triggers or irritants",
      "Consider over-the-counter antihistamines if itching is present",
    ],
    severe: [
      "URGENT: Schedule an appointment with a dermatologist immediately",
      "If symptoms are rapidly worsening, consider urgent care",
      "Do not self-medicate - professional evaluation is important",
      "Take photos and notes to share with your healthcare provider",
      "Watch for signs of infection (increased redness, warmth, pus)",
      "Prioritize rest and avoid activities that aggravate the condition",
    ],
  }

  return baseSuggestions[severity]
}
